server:
  port: 8888

logging:
  file:
    name: logs/mylog.log

spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.191:3306/apitest
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

